services:
   ecomm-app:
     container_name: ecomm-app
     image: ecomm-app
     build: .
     depends_on:
       - mongo
     ports:
       - "3000:3000"
     networks:
       - frontend
       - backend
   mongo:
     container_name: mongo
     image: mongo
     volumes:
       - mongodata:/data/db
     ports:
       - "27017:27017"
     networks:
       - backend
   mongo-express:
     container_name: mongo-express
     image: mongo-express
     ports:
       - "8081:8081"
     environment:
       - ME_CONFIG_MONGODB_SERVER=mongo
       - ME_CONFIG_MONGODB_PORT=27017
       - ME_CONFIG_SITE_BASEURL=/mongo-express
     depends_on:
       - mongo
     networks:
       - backend
       - frontend
   proxy:
     container_name: proxy
     image: nginx
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt
       - ./ssl/localhost.key:/etc/ssl/private/localhost.key
     depends_on:
       - ecomm-app
       - mongo-express
     ports:
       - "80:80"
       - "443:443"
     networks:
       - frontend
volumes:
   mongodata:
networks:
   backend:
     internal: True
   frontend:
